/**
 * ==============================================================================
 * 📝 CAPTIONER - CENTRAL UI CONTENT & CONFIGURATION FILE
 * ==============================================================================
 * Is file se aap pure frontend ka content, text, labels, presets, aur default
 * captions easily change kar sakte hain. Jahan bhi change karenge, UI automatically
 * update ho jayegi!
 * ==============================================================================
 */

export const UI_CONTENT = {
  // 1. Site & Brand Information
  brand: {
    name: 'Captioneer',
    tagline: 'AI Video Caption Studio',
    badge: '',
    version: 'v1.0.0',
  },

  // 2. Top Navigation Bar Content
  topNavbar: {
    projectTitleFallback: 'Untitled Video Project',
    guidesButton: 'Safe Guides',
    guidesTooltip: 'Toggle Social Media Safe-Area Boundaries',
    undoTooltip: 'Undo (Ctrl+Z)',
    redoTooltip: 'Redo (Ctrl+Y)',
    uploadButton: 'Upload Video',
    exportButton: 'Export Video',
    aspectRatios: [
      { id: '9:16', label: '9:16', description: 'TikTok / Reels / Shorts (Vertical)' },
      { id: '16:9', label: '16:9', description: 'YouTube / Widescreen (Horizontal)' },
      { id: '1:1', label: '1:1', description: 'Instagram / Feed (Square)' },
    ],
  },

  // 3. Left Sidebar: Caption Transcript List
  captionInspector: {
    title: 'Captions',
    addButton: 'Add Cue',
    searchPlaceholder: 'Search transcript...',
    emptyStateTitle: 'No captions found',
    emptyStateDescription: 'Click "+ Add Cue" or upload a video to auto-generate AI transcripts.',
    wordsTotalSuffix: 'words total',
    cuesCountSuffix: 'cues',
    engineBadge: 'Whisper Large v3',
    cardActions: {
      jumpTooltip: 'Jump playhead to this caption',
      splitTooltip: 'Split caption cue into two',
      mergeTooltip: 'Merge with next caption',
      deleteTooltip: 'Delete caption cue',
      timeFormatTooltip: 'Click to edit timestamp',
    },
  },

  // 4. Right Sidebar: Style & Presets Studio
  stylePanel: {
    title: 'Style Studio',
    tabs: [
      { id: 'presets', label: 'Presets' },
      { id: 'typography', label: 'Font' },
      { id: 'colors', label: 'Colors' },
      { id: 'effects', label: 'Effects' },
    ],
    presetsSectionTitle: 'Trending Caption Presets',
    fontFamilyLabel: 'Font Family',
    fontSizeLabel: 'Font Size',
    uppercaseLabel: 'Uppercase Text',
    uppercaseDescription: 'Convert all subtitle words to uppercase',
    boldLabel: 'Bold Font',
    boldDescription: 'Thick high-visibility typography',
    italicLabel: 'Italic Text',
    activeWordColorLabel: 'Active Word Color',
    primaryTextColorLabel: 'Inactive Words Color',
    strokeColorLabel: 'Text Outline / Stroke Color',
    strokeWidthLabel: 'Outline Stroke Width',
    shadowDepthLabel: 'Drop Shadow Depth',
    animationTypeLabel: 'Active Word Animation',
    verticalPositionLabel: 'Vertical Position on Screen',
    backgroundBoxLabel: 'Background Highlight Box',
    backgroundBoxDescription: 'Enclose caption words in a dark translucent pill',
    boxBgColorLabel: 'Box Background Color',
    boxCornerRadiusLabel: 'Box Corner Radius',

    // Available Animation Types
    animationOptions: [
      { id: 'pop', label: 'Viral Pop' },
      { id: 'bounce', label: 'Bounce' },
      { id: 'glow', label: 'Karaoke Glow' },
      { id: 'slide', label: 'Slide Up' },
      { id: 'fade', label: 'Subtle Fade' },
      { id: 'none', label: 'Static' },
    ],

    // Available Font Options
    fontOptions: [
      { label: 'Montserrat (Viral Bold)', value: 'Montserrat' },
      { label: 'Inter (Clean Modern)', value: 'Inter' },
      { label: 'Impact (Punchy Heavy)', value: 'Impact' },
      { label: 'Arial (Standard)', value: 'Arial' },
      { label: 'Rubik (Rounded)', value: 'Rubik' },
    ],

    // Built-in Presets
    presets: [
      {
        id: 'hormozi-pop',
        name: 'Hormozi Viral Pop',
        description: 'Bold yellow pop-in active words with heavy dark stroke',
        previewText: 'VIRAL POP',
        style: {
          presetId: 'hormozi-pop',
          fontFamily: 'Montserrat',
          fontSize: 42,
          textColor: '#FFFFFF',
          activeWordColor: '#FFE600',
          strokeColor: '#000000',
          strokeWidth: 6,
          shadowColor: '#000000',
          shadowOffset: 4,
          uppercase: true,
          bold: true,
          animationType: 'pop',
          hasBox: false,
          positionY: 78,
        },
      },
      {
        id: 'karaoke-glow',
        name: 'Karaoke Cyan Glow',
        description: 'Smooth glowing cyan word highlight for storytelling',
        previewText: 'GLOW CUE',
        style: {
          presetId: 'karaoke-glow',
          fontFamily: 'Inter',
          fontSize: 38,
          textColor: '#94A3B8',
          activeWordColor: '#00F0FF',
          strokeColor: '#000000',
          strokeWidth: 3,
          shadowColor: 'rgba(0, 240, 255, 0.6)',
          shadowOffset: 6,
          uppercase: false,
          bold: true,
          animationType: 'glow',
          hasBox: false,
          positionY: 78,
        },
      },
      {
        id: 'boxed-pill',
        name: 'Boxed Pill Highlight',
        description: 'Clean rounded dark box with active yellow highlight',
        previewText: 'BOXED PILL',
        style: {
          presetId: 'boxed-pill',
          fontFamily: 'Inter',
          fontSize: 34,
          textColor: '#FFFFFF',
          activeWordColor: '#FFE600',
          strokeColor: 'transparent',
          strokeWidth: 0,
          shadowColor: 'transparent',
          shadowOffset: 0,
          uppercase: false,
          bold: true,
          animationType: 'pop',
          hasBox: true,
          boxBackground: 'rgba(15, 17, 26, 0.85)',
          boxPadding: 12,
          boxRadius: 12,
          positionY: 80,
        },
      },
      {
        id: 'clean-minimal',
        name: 'Clean Minimalist',
        description: 'Understated elegant typography with soft drop shadow',
        previewText: 'Clean Aesthetic',
        style: {
          presetId: 'clean-minimal',
          fontFamily: 'Inter',
          fontSize: 32,
          textColor: '#FFFFFF',
          activeWordColor: '#FFFFFF',
          strokeColor: 'rgba(0,0,0,0.5)',
          strokeWidth: 2,
          shadowColor: 'rgba(0,0,0,0.6)',
          shadowOffset: 2,
          uppercase: false,
          bold: false,
          animationType: 'fade',
          hasBox: false,
          positionY: 82,
        },
      },
      {
        id: 'cyber-neon',
        name: 'Cyber Neon Emerald',
        description: 'Vibrant green neon pulse with cyber aesthetic',
        previewText: 'CYBER NEON',
        style: {
          presetId: 'cyber-neon',
          fontFamily: 'Montserrat',
          fontSize: 40,
          textColor: '#E2E8F0',
          activeWordColor: '#10B981',
          strokeColor: '#042F2E',
          strokeWidth: 5,
          shadowColor: 'rgba(16, 185, 129, 0.7)',
          shadowOffset: 5,
          uppercase: true,
          bold: true,
          animationType: 'bounce',
          hasBox: false,
          positionY: 78,
        },
      },
    ],
  },

  // 5. Bottom Interactive Timeline
  timeline: {
    videoTrackLabel: 'Video',
    captionsTrackLabel: 'Captions',
    tracksCountLabel: '2 Tracks',
    zoomInTooltip: 'Zoom in timeline',
    zoomOutTooltip: 'Zoom out timeline',
    jumpBackTooltip: 'Jump -5s (Shift+Left)',
    jumpForwardTooltip: 'Jump +5s (Shift+Right)',
    playTooltip: 'Play / Pause (Space)',
  },

  // 6. Upload & Transcribe Modal
  uploadModal: {
    title: 'Upload Video',
    description: '',
    dropzoneTitle: 'Drag video here',
    dropzoneSubtitle: '',
    supportedFormatsHint: '(Max upload 500MB)',
    languageLabel: 'Spoken Language',
    promptLabel: 'Context Prompt (Optional)',
    promptPlaceholder: 'Custom names, acronyms, or specific terminology...',
    cancelButton: 'Cancel',
    submitButton: 'Transcribe Video',
    uploadingMessage: 'Uploading video...',
    transcribingMessage: 'Transcribing speech...',
    completeMessage: 'Transcription complete!',
    languages: [
      { label: 'Auto Detect Language', value: '' },
      { label: 'English', value: 'en' },
      { label: 'Urdu', value: 'ur' },
      { label: 'Hindi', value: 'hi' },
      { label: 'Spanish', value: 'es' },
      { label: 'French', value: 'fr' },
      { label: 'German', value: 'de' },
      { label: 'Arabic', value: 'ar' },
      { label: 'Japanese', value: 'ja' },
    ],
  },

  // 7. Video Export & Burn-In Modal
  exportModal: {
    title: 'Export Video with Subtitles',
    description: '',
    successTitle: 'Video Ready for Download! 🎉',
    successSubtitle: 'Subtitles have been hardcoded onto your video.',
    summaryTitle: 'Export Configuration Details',
    aspectRatioLabel: 'Aspect Ratio',
    durationLabel: 'Duration',
    captionsCountLabel: 'Captions Count',
    activePresetLabel: 'Active Preset',
    renderingMessage: 'Rendering & Burning Subtitles...',
    renderingSubtitle: 'FFmpeg is encoding high-quality video frames with styled typography',
    cancelButton: 'Cancel',
    startButton: 'Start Video Export',
    downloadButton: 'Download MP4 File',
    doneButton: 'Done',
  },

  // 8. Default Initial Mock Data (Shown on page load)
  initialData: {
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    videoMetadata: {
      originalName: 'captioneer_demo_video.mp4',
      duration: 12.0,
      width: 1080,
      height: 1920,
      fps: 30,
      sizeBytes: 8450120,
      videoId: 'sample-video-default',
    },
    subtitles: [
      {
        id: 'cue-1',
        start: 0.2,
        end: 2.8,
        text: 'Welcome to Captioneer, the modern AI subtitle editor.',
        words: [
          { word: 'Welcome', start: 0.2, end: 0.6 },
          { word: 'to', start: 0.65, end: 0.85 },
          { word: 'Captioneer,', start: 0.9, end: 1.4 },
          { word: 'the', start: 1.45, end: 1.65 },
          { word: 'modern', start: 1.7, end: 2.0 },
          { word: 'AI', start: 2.05, end: 2.25 },
          { word: 'subtitle', start: 2.3, end: 2.55 },
          { word: 'editor.', start: 2.6, end: 2.8 },
        ],
      },
      {
        id: 'cue-2',
        start: 3.0,
        end: 5.6,
        text: 'Instantly generate viral word-by-word animated captions.',
        words: [
          { word: 'Instantly', start: 3.0, end: 3.4 },
          { word: 'generate', start: 3.45, end: 3.85 },
          { word: 'viral', start: 3.9, end: 4.2 },
          { word: 'word-by-word', start: 4.25, end: 4.8 },
          { word: 'animated', start: 4.85, end: 5.2 },
          { word: 'captions.', start: 5.25, end: 5.6 },
        ],
      },
      {
        id: 'cue-3',
        start: 5.8,
        end: 8.5,
        text: 'Customize typography, colors, animations, and safe zones.',
        words: [
          { word: 'Customize', start: 5.8, end: 6.3 },
          { word: 'typography,', start: 6.35, end: 6.85 },
          { word: 'colors,', start: 6.9, end: 7.3 },
          { word: 'animations,', start: 7.35, end: 7.9 },
          { word: 'and', start: 7.95, end: 8.1 },
          { word: 'safe', start: 8.15, end: 8.3 },
          { word: 'zones.', start: 8.32, end: 8.5 },
        ],
      },
      {
        id: 'cue-4',
        start: 8.8,
        end: 11.6,
        text: 'Export with professional FFmpeg subtitle burn-in in seconds!',
        words: [
          { word: 'Export', start: 8.8, end: 9.25 },
          { word: 'with', start: 9.3, end: 9.45 },
          { word: 'professional', start: 9.5, end: 10.0 },
          { word: 'FFmpeg', start: 10.05, end: 10.5 },
          { word: 'subtitle', start: 10.55, end: 10.9 },
          { word: 'burn-in', start: 10.95, end: 11.3 },
          { word: 'in', start: 11.35, end: 11.45 },
          { word: 'seconds!', start: 11.47, end: 11.6 },
        ],
      },
    ],
  },
};
